name:  Output from jobs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Set output
      id: set-output
      shell: bash
      run: |
        echo "age=23" >> $GITHUB_OUTPUT
    
    - name: Get output
      id: get-output
      run: |
        echo "Value of age is ${{ steps.set-output.outputs.age }}"


# Note: We can not access the output of the step in any other job. output of the steps is accessible only in that perticuller job