name: Deployment on AWS
on:
  push:
    branches:
      - stage
      - quality
      - main
jobs:
  get-environment:
    name: Get environment
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout github code
      id: checkout-id
      uses: actions/checkout@v4
    - name: Set environment
      id: setenv
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
          echo "my_env=stage" >> $GITHUB_OUTPUT          
        elif [[ "${{ github.ref }}" == "refs/heads/quality" ]]; then
          echo "my_env=quality" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
          echo "my_env=production" >> $GITHUB_OUTPUT
        fi
        
  # Audit Extract
  # =======================================================
  audit-extract:
    name: Deploying Audit Extract
    runs-on: ubuntu-latest
    needs: get-environment
    environment:
      name: ${{ needs.get-environment.outputs.my_env }}
    
    steps:
    - name: Test Variables
      id: test-variables
      run:
        echo "${{ vars.ENVIRONMENT }}"
        echo "${{ vars.AWS_DEFAULT_REGION }}"