name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Print Values of environment
      run: |
        echo ${{ secrets.DOCKERHUB_USERNAME }}
        echo ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      run: |
        docker build -t munawarraza/demoapp:$(date +%F-%H-%M-%S) .
        docker push  munawarraza/demoapp:$(docker images | awk '{print $0}' |awk 'NR==2 {print $2}')
