name: Node.js CI
#run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  get-environment:
    name: Get environment
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout github code
      id: checkout-id
      uses: actions/checkout@v4
    - id: setenv
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "my_env=stage" >> $GITHUB_OUTPUT          
        elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
          echo "my_env=production" >> $GITHUB_OUTPUT
        fi
  build:
    runs-on: ubuntu-latest
    needs: get-environment
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Print Values of environment
      run: |
        echo "Printing the secrets values"
        echo ${{ secrets.DOCKERHUB_USERNAME }}
        echo ${{ secrets.DOCKERHUB_TOKEN }}
        echo "Printing the variable value"
        echo ${{ vars.DOCKERHUB_USERNAME }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      run: |
        docker build -t munawarraza/demoapp:latest .
        docker push  munawarraza/demoapp:latest
