name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: docker build . --file Dockerfile --tag munawarraza/demoapp:$(date +%F)
    - name: Push Image to Registry
      run: docker push munawarraza/demoapp:$(date +%F)
    
